#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh && break ; done

FILE=../../s/x86-helloworld-gcc
CMDS='
S | grep .init_array
'
EXPECT='[17] . 0x0000059c rw- va=0x0804959c sz=0x00000004 vsz=00000004 .init_array
'
EXPECT_ERR=''

run_test
