#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="ARCompact ISA instruction check"
FILE=malloc://512
CMDS='
e asm.arch=arc
e asm.bits=16
wx 0a22803f00002839 @ 0x144
s 0x144
pi 1
'
EXPECT='mov gp, 0x3928
'

run_test

NAME="ARCompact ISA jump check"
FILE=malloc://512
CMDS='
e asm.arch=arc
e asm.bits=16
wx e820a201 @ 0x138
s 0x138
ao 1~jump
'
EXPECT='jump: 0x00000144
'

run_test

NAME="ARCompact ISA jump check [2]"
FILE=malloc://512
CMDS='
e asm.arch=arc
e asm.bits=16
wx e820a201 @ 0x138
s 0x138
pi 1
'
EXPECT='lpnz 0x00000144
'
run_test

NAME="ARCompact ISA instruction length"
FILE=malloc://512
CMDS='
e asm.arch=arc
e asm.bits=16
wx 0a22803f00002839 @ 0
wx cf7200003439 @ 8
wx 422bbc80 @ 8+6
wx 00db @ 8+6+4
ao 4~size
'
EXPECT='size: 8
size: 6
size: 4
size: 2
'
run_test
