#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
CMDS='
e asm.arch=x86
e asm.bits=32
wa mov eax, 0x21
   pi 1;s+$l
wa nop
   pi 1;s+$l
wa int 0x80
   pi 1;s+$l
?v $$
'
EXPECT='mov eax, 0x21
nop
int 0x80
0x8
'

run_test
