#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
CMDS='
e asm.arch=x86
e asm.bits=32
wa mov eax, 0x21
   pi 1;s+$l
wa nop
   pi 1;s+$l
wa int 0x80
   pi 1;s+$l
?v $$
'
EXPECT='mov eax, 0x21
nop
int 0x80
0x8
'

run_test

NAME="eax vs rax"
CMDS='
e asm.arch=x86
e asm.bits=32
pa mov eax, 33
pa mov rax, 33
e asm.bits=64
pa mov eax, 33
pa mov rax, 33
'
EXPECT='b821000000
b821000000
b821000000
48c7c021000000
'

run_test
