#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# -------------------------------
# MULSD instruction
NAME="x86 SSE: [MULSD]"
BROKEN=1
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx 66f3f20f59ff
pi 1
'
EXPECT='mulsd xmm7, xmm7
'
run_test

# -------------------------------
# MULSS instruction
NAME="x86 SSE: [MULSS]"
BROKEN=1
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx 66f2f0f59ff
pi 1
'
EXPECT='mulss xmm7, xmm7
'
run_test

# -------------------------------
# MULPD instruction
NAME="x86 SSE: [MULPD]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx 660f59ff
pi 1
'
EXPECT='mulpd xmm7, xmm7
'
run_test

# -------------------------------
# MULSD instruction
NAME="x86 SSE: [MULSD]"
BROKEN=1
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx f2660f59ff
pi 1
'
EXPECT='mulsd xmm7, xmm7
'
run_test

# -------------------------------
# MULPS instruction
NAME="x86 SSE: [MULPS]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx 0f59ff
pi 1
'
EXPECT='mulps xmm7, xmm7
'
run_test

