#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=../../s/x86-simple
CMDS='
/x 5b
pi 1 @ hit0_0
'
EXPECT='0x08048065 hit0_0 5bb801000000bb2a00
pop ebx
'
EXPECT_ERR='hits: 1
'

run_test
