#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

# "!" - run commands (via system)

NAME='!'
FILE=-
ARGS=
CMDS='
!echo fuck
!echo yeah
'
EXPECT='fuck
yeah'
run_test

NAME='!'
FILE=-
ARGS=
CMDS='
?e fuck
?e yeah
'
EXPECT='fuck
yeah'
run_test
