#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='pD -5 @ 0'
BROKEN=
FILE=malloc://512
ARGS=
CMDS='e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f
pD -5
'
EXPECT='            0x00000000    b801000000   mov eax, 0x1
------
            0xfffffffffffffffb    ff           invalid
            0xfffffffffffffffc    ff           invalid
            0xfffffffffffffffd    ff           invalid
            0xfffffffffffffffe    ff           invalid
            0xffffffffffffffff    ff           invalid
------
            0xfffffffffffffffc    ff           invalid
            0xfffffffffffffffd    ff           invalid
            0xfffffffffffffffe    ff           invalid
            0xffffffffffffffff    ff           invalid
            0x00000000    b801000000   mov eax, 0x1
------
            0xfffffffffffffffd    ff           invalid
            0xfffffffffffffffe    ff           invalid
            0xffffffffffffffff    ff           invalid
            0x00000000    b801000000   mov eax, 0x1
------
            0xfffffffffffffffe    ff           invalid
            0xffffffffffffffff    ff           invalid
            0x00000000    b801000000   mov eax, 0x1
------
            0xffffffffffffffff    0000         add [rax], al
            0x00000001    0000         add [rax], al
            0x00000003    ff           invalid
------
'

NAME='pD 5 @ 0'
BROKEN=
FILE=malloc://512
ARGS=
CMDS='e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f
pD 5
'
EXPECT='            0x00000000    b801000000   mov eax, 0x1
------
            0x00000001    0100         add [rax], eax
            0x00000003    0000         add [rax], al
            0x00000005    4839ca       cmp rdx, rcx
------
            0x00000002    0000         add [rax], al
            0x00000004    004839       add [rax+0x39], cl
------
            0x00000003    0000         add [rax], al
            0x00000005    4839ca       cmp rdx, rcx
------
            0x00000004    004839       add [rax+0x39], cl
            0x00000007    ca7f00       retf 0x7f
------
'

NAME='pd 5 @ 0'
BROKEN=
FILE=malloc://512
ARGS=
CMDS='e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f
pd 5
'
EXPECT='                                    0x00000000    b801000000   mov eax, 0x1
            0x00000005    4839ca       cmp rdx, rcx
            0x00000008    7f00         jg 0xa
            0x0000000a    0000         add [rax], al
            0x0000000c    0000         add [rax], al
'

NAME='pd -4 @ 1'
BROKEN=
FILE=malloc://512
ARGS=
CMDS='e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f
pd -4 @ 1
'
EXPECT='                                    0x00000000    b801000000   mov eax, 0x1
            0x00000005    4839ca       cmp rdx, rcx
            0x00000008    7f00         jg 0xa
            0x0000000a    0000         add [rax], al
            0x0000000c    0000         add [rax], al
'

NAME='pd -5 @ 6'
BROKEN=
FILE=malloc://512
ARGS=
CMDS='
e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx 20c09fe5b8010000004839ca7f
pd -5 @ 6
'
EXPECT='            0x00000000    20c0         and al, al
            0x00000002    9f           lahf
            0x00000003    e5b8         in eax, 0xb8
            0x00000005    0100         add [rax], eax
            0xfffffffffffffffc    ff           invalid
            0xfffffffffffffffd    ff           invalid
            0xfffffffffffffffe    ff           invalid
            0xffffffffffffffff    00           invalid
'
run_test


NAME='pd -2 @ 5'
BROKEN='Yes'
FILE=malloc://512
ARGS=
CMDS='
e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx 20c09fe5b8010000004839ca7f
pd -2 @ 5
'
EXPECT='            0x00000002    9f           lahf
            0x00000003    e5b8         in eax, 0xb8
'
run_test

NAME='pd -3 @ 6'
BROKEN=
FILE=malloc://512
ARGS=
CMDS='
e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx 20c09fe5b8010000004839ca7f
pd -3 @ 6
'
EXPECT='            0x00000002    9f           lahf
            0x00000003    e5b8         in eax, 0xb8
            0x00000005    0100         add [rax], eax
'
run_test

NAME='pd -5 @ 5'
BROKEN=
FILE=malloc://512
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=64
wx 20c09fe5b8010000004839ca7f
pd -5 @ 5
'
EXPECT='            0x00000000    20c0         and al, al
            0x00000002    9f           lahf
            0x00000003    e5b8         in eax, 0xb8
            0xfffffffffffffffc    ff           invalid
            0xfffffffffffffffd    ff           invalid
            0xfffffffffffffffe    ff           invalid
            0xffffffffffffffff    00           invalid
'
run_test
