#!/bin/sh

. ../tests.sh

## "f" - set flags

# No args should not crash (bug report #56).
FILE=malloc://1024
ARGS=
CMDS='f'
EXPECT=
run_test

# Add flags.
FILE=malloc://1024
ARGS=
CMDS='
f cat
f rimmer 12
f lister 32@666
f kryten 32 666
f+skutter 1 @ 12
f
'
EXPECT='0x0000000c 1 skutter
0x0000029a 32 kryten
0x0000029a 32 lister
0x00000000 12 rimmer
0x00000000 64 cat'
run_test
