#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

## "?e" - echo string

NAME='?e'
FILE=malloc://1024
ARGS=
CMDS='
?e fuck
?e yeah
'
EXPECT='fuck
yeah'
run_test


## "?v" - hex value of math expr

# No crash if no arguments are given.
NAME='?v'
FILE=malloc://1024
ARGS=
CMDS='?v'
EXPECT='0x0'
run_test

# File size reporting.
NAME='?v'
FILE=malloc://1024
ARGS=
CMDS='?v $s'
EXPECT='0x400'
run_test
