#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

## "s" - seek to address

# Seeking in hex, decimal and octal in an empty file.
touch empty.tmp
NAME='s'
FILE=empty.tmp
ARGS=
CMDS='
s 0x666
s
s 15
s
s 034
s
s 0
s+2
s -1
s
s+0x4
s
'
EXPECT='0x666
0xf
0x1c
0x1
0x5'
run_test
rm -f empty.tmp

# Seeking in hex, decimal and octal.
NAME='s'
FILE=malloc://1024
ARGS=
CMDS='
s 0x666
s
s 15
s
s 034
s
s 0
s+2
s -1
s
s+0x4
s
'
EXPECT='0x666
0xf
0x1c
0x1
0x5'
run_test


## "s+"/"s-" - seek undo/redo

NAME='s+/s-'
FILE=malloc://1024
ARGS=
CMDS='
s 0x10
s 0x20
s 0x30
s 0x40
?v $$
s-
?v $$
s+
?v $$
s-
?v $$
s-
?v $$
s-
?v $$
s-
?v $$
'
EXPECT='0x40
0x30
0x40
0x30
0x20
0x10
0x0'
run_test
