#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

## "/" - search for string

# Tests ASCII searching
# For some reason searches entire address range rather than just
# 1024 bytes XXX
NAME='/'
FILE=malloc://1024
ARGS=
CMDS='
w test
w test@333
w test@666
b 1024
/ test
'
EXPECT='0x00000000 hit0_0 "test"
0x0000014d hit0_1 "test"
0x0000029a hit0_2 "test"
'
EXPECT_ERR='Searching 4 bytes from 0x00000000 to 0x00000400: 74 65 73 74 
hits: 3
'
run_test


## "/c" -- search for asm code

# No crash if no arguments are given.
NAME='/c'
FILE=malloc://1024
ARGS=
CMDS='/c?'
EXPECT=
run_test


## "/x" -- search hexadecimal

NAME='/x'
FILE=malloc://1024
ARGS=
CMDS='wx 01020304 @ 0x100
/x 01020304
?v hit0_0'
EXPECT='0x00000100 hit0_0 010203040000000000000000
0x100
'
EXPECT_ERR='hits: 1
'
run_test

NAME='/x (va)'
FILE=../s/x86-simple
ARGS=
CMDS='
/x 5b
pi 1 @ hit0_0
'
EXPECT='0x08048065 hit0_0 5bb801000000bb2a00
pop ebx
'
EXPECT_ERR='hits: 1
'
run_test
