#!/bin/sh

. ../tests.sh

## "/" - search for string

# Tests ASCII searching
# For some reason searches entire address range rather than just
# 1024 bytes XXX
NAME='/'
FILE=malloc://1024
ARGS=
CMDS='
w test
w test@333
w test@666
/ test @0:1024
'
EXPECT='Searching 4 bytes from 0x00000000 to 0x00000400: 74 65 73 74 
hits: 3  hit0_0 .. hit0_2
hit0_0
hit0_1
hit0_2'
run_test


## "/c" -- search for asm code

# No crash if no arguments are given.
NAME='/c'
FILE=malloc://1024
ARGS=
CMDS='/c?'
EXPECT=
run_test
