#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

NAME='o-'
FILE=malloc://1024
ARGS=
CMDS='o-`o~[1]`;o'
EXPECT=
run_test

NAME='o -'
FILE=malloc://1024
ARGS=
CMDS='o -;o~?'
EXPECT='2'
run_test
