#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2013  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

## "wa" - write opcode

NAME='wa'
FILE=malloc://1024
ARGS='-a x86 -b 32'
CMDS='
"wa nop;mov eax,33"
e asm.profile=simple
pi 2
'
EXPECT='nop
mov eax, 0x21
'
run_test


## "wx" - write hex value

# Writing of bytes.
NAME='wx'
FILE=malloc://1024
ARGS=
CMDS='
wx 010203
p8 3
'
EXPECT='010203
'
run_test


## "wo" - write in block with operation

# Batch adding to bytes works (bug report #59).
NAME='wo'
FILE=malloc://8
ARGS='-w'
CMDS='
wx 0001020304050607
woa 01 @ 0j8
x
p8 8
woa 01 @ 0!8
p8 8
'
EXPECT='0102030405060708
0203040506070809
'
run_test
