#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

## "/" - search for string

# Tests ASCII searching
# For some reason searches entire address range rather than just
# 1024 bytes XXX
NAME='/'
FILE=malloc://1024
ARGS=
CMDS='
w test
w test@333
w test@666
/ test @0:1024
'
EXPECT='hit0_0
hit0_1
hit0_2
'
run_test


## "/c" -- search for asm code

# No crash if no arguments are given.
NAME='/c'
FILE=malloc://1024
ARGS=
CMDS='/c?'
EXPECT=
run_test


## "/x" -- search hexadecimal

NAME='/x'
FILE=malloc://1024
ARGS=
CMDS='wx 01020304 @ 0x100
/x 01020304
?v hit0_0'
EXPECT='hit0_0
0x100
'
run_test
