#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh
NAME='ahc'
FILE=malloc://16
CMDS='
e asm.arch=x86
e asm.bits=32
wx ebfe
ahl 5
ahc 0x25
ahf 0x25
ao 1~jump,fail,size[1]
'
EXPECT='5
0x00000025
0x00000025
'
run_test
