#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='o-'
FILE=malloc://1024
ARGS=
CMDS='o-`o~[1]`;o'
EXPECT=
run_test

NAME='o -'
FILE=malloc://1024
ARGS=
CMDS='o -;o~?'
EXPECT='2
'
run_test

NAME='om'
FILE=malloc://1024
ARGS=
CMDS='om `o~[1]` 0x4000
om~?'
EXPECT='2
'
run_test

NAME='om2'
FILE=malloc://1024
ARGS=
CMDS='om `o~[1]` 0x4000
om `o~[1]` 0x4000
om~?'
EXPECT='2
'
run_test
