#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

## cache

# Basic cache usage.
FILE=malloc://1024
NAME='io.cache;wx'
ARGS=
CMDS='
e io.cache=1
wx 010203
p8 3
'
EXPECT='010203'
run_test
