#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

## ">" - redirection

# Test basic redirection.
NAME="pb>x;!wc -c x"
FILE=malloc://1024
ARGS=
CMDS='
# Normal redirect.
pb 10 > dump
!wc -c dump|awk "{print \$1}"
# Redirect with output bigger than CONS_MAX_USER.
pb 12800 > dump
!wc -c dump|awk "{print \$1}"
!rm -f dump
'
EXPECT='81
102401
'

EXPECT_ERR=''
run_test
