#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2013  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

## grep

# Basic grep.
NAME='px~:1[1]'
FILE=malloc://1024
ARGS=
CMDS='
wx 10203040
px~:1[1]
'
EXPECT='1020
'
run_test

NAME='px~?'
FILE=malloc://1024
ARGS=
CMDS='
wx 10203040
b 128
px~?
'
EXPECT='9
'
run_test

NAME='i;$s'
FILE=malloc://1024
ARGS=
CMDS='?v `i~size[1]`-$s;?? ?e works'
EXPECT='0x0
works
'
run_test

NAME='?e~[0]'
FILE=malloc://1024
ARGS=
BROKEN=
CMDS='?e 0x3~[0];?e 0x999~[0]'
EXPECT='0x3
0x999
'
run_test

NAME='?e~[0]'
BROKEN=
FILE=malloc://1024
ARGS=
CMDS='?e hello world~[0]
?e hello world~[1]
'
EXPECT='hello
world
'
run_test
