#!/bin/sh

# GPL 3+ - Copyright (C) 2013 pancake

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='graphdiff segfault'
FILE=-
BROKEN=
ARGS=
CMDS='cg /
'
EXPECT='fcn.00000000  0x0 |     NEW  (0.000000)
'
run_test
