#!/bin/sh

# GPL 3+ - Copyright (C) 2012 pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='graphdiff segfault'
FILE=-
BROKEN=1
ARGS=
CMDS='cg /
'
EXPECT=''
run_test
