#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

## Arithmetic expressions

FILE=malloc://1024
NAME="10+30"
ARGS=
CMDS='
?v 0x10+0x30
'
EXPECT='0x40'
run_test

# TODO: needs to integrate calc.c into num_math!
BROKEN=1
FILE=malloc://1024
NAME="1+3*2"
ARGS=
CMDS='?v 1+3*2'
EXPECT='0x7'
run_test

FILE=malloc://1024
NAME="(1+3)*2"
ARGS=
CMDS='?v (1+3)*2'
EXPECT='0x8'
run_test
