#!/bin/sh

# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

## Variables

FILE=malloc://1024
NAME='$variables (malloc)'
ARGS=
CMDS='
e asm.arch = x86
e asm.bits =  32

?e Current seek.
?v $$
s 42
?v $$
s-
?v $$
?e \n

?e Current io offset.
?v $o
s 42
?v $o
s-
?v $o
?e \n

?e File size reporting.
?v $s
?e \n

?e Block size.
b 123;?v $b;? $b
?e \n

?e Jump address.
wa jmp 0x30
?v $j
wa jz 0x01
?v $j
wa xor eax, eax
?v $j
?e \n

?e Jump fail address.
wa jmp 0x30
?v $f
wa jz 0x01
?v $f
wa xor eax, eax
?v $f
?e \n

?e Opcode memory reference.
wa mov eax, [0x500]
?v $r
wa mov eax, ebx
?v $r
?e \n

?e Opcode length.
wa xor eax, eax
?v $l
wa mov esp, 0x1
?v $l
wa ret
?v $l
?e \n

?e End of (assembly) block?
wa inc eax
?v $e
wa jmp 0x01
?v $e
wa ret
?v $e
wa call 0x01
?v $e
?e \n

?e Get value of configuration variable.
?v ${asm.bits}
?e \n

?e Last comparision value.
? 5 + 3
?v $?
? 0
?v $?
?e \n
'
EXPECT='Current seek.
0x0
0x2a
0x0

Current io offset.
0x0
0x2a
0x0

File size reporting.
0x400

Block size.
0x7b
123 0x7b 0173 0000:007B 01111011 0.000000

Jump address.
0x30
0x1
0xffffffffffffffff

Jump fail address.
0xffffffffffffffff
0x6
0xffffffffffffffff

Opcode memory reference.
0x500
0xffffffffffffffff

Opcode length.
0x2
0x5
0x1

End of (assembly) block?
0x0
0x1
0x1
0x0

Get value of configuration variable.
0x20

Last comparision value.
8 0x8 010 0000:0008 00001000 0.000000
0x8
0 0x0 00 0000:0000 00000000 0.000000
0x0'
run_test
