#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

## Arithmetic expressions

NAME='basic'
FILE=malloc://1024
ARGS=
CMDS='
?v 0x10+0x30
?v 1+3*2
?v (1+3)*2
'
EXPECT='0x40
0x7
0x8
'
run_test

BROKEN=
NAME='sum'
FILE=-
ARGS=
CMDS='
f a@3
?v a+3
?v a +3
?v a+ 3
?v 3 + 3
'
EXPECT='0x6
0x6
0x6
0x6
'
run_test
