#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='pdn look at bytes'
BROKEN=
FILE=malloc://512
ARGS=
CMDS='
e anal.hasnext=0
e asm.arch=x86
e asm.bits=64

wx b8010000004839ca7f26
pdn 5
pdn 5 x86 32
pdn 3 x86 64 @ 5
pdn 3 x86 32 @ 5
'
EXPECT='0x00000000       b801000000  mov eax, 0x1
0x00000000       b801000000  mov eax, 0x1
0x00000005           4839ca  cmp rdx, rcx
0x00000005               48  dec eax
0x00000006             39ca  cmp edx, ecx
'
run_test
