#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

. ../tests.sh

## grep

# Basic grep.
FILE=malloc://1024
ARGS=
CMDS='
wx 10203040
px~:1[1]
'
EXPECT='1020'
run_test
