#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=1
NAME="visual hex scroll"
CMDS='
wx 4889e54889e5
Vjq
s
'
EXPECT='0x10
'

run_test

NAME="visual op scroll"
BROKEN=1
CMDS='
wx 4889e54889e5
Vpjq
s
'
EXPECT='0x4
'

run_test
