#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=
NAME="visual hex scroll"
CMDS='
e scr.interactive=true
e asm.arch=x86
e asm.bits=64
wx 4889e54889e5
Vjq
s
'
EXPECT='0x10
'

run_test

NAME="visual op scroll"
BROKEN=
CMDS='
e asm.arch=x86
e asm.bits=64
e scr.interactive=true
wx 4889e54889e5
Vpjq
s
'
EXPECT='0x3
'

run_test

BROKEN=
NAME="visual hex pP scroll"
CMDS='
e asm.arch=x86
e asm.bits=64
e scr.interactive=true
wx 4889e54889e5
VpPjq
s
'
EXPECT='0x10
'
run_test
