#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="esil x86-64"
BROKEN=1
CMDS='
?e
e asm.arch=x86
e asm.bits=64
wx 488d7768
ao~opcode,esil
'
EXPECT='
opcode: lea rsi, [rdi+0x68]
esil: rsi=rdi+68,rip+=4
'

run_test
